### ISSUE TITLE
Webdriver: Message: 'The browser appears to have exited before we could connect. after 2h run. Why?

### ISSUE THREAD

**Issue by KgBC** [KgBC/just-dice-bot#11]
Traceback (most recent call last):
  File "just-dice-bot.py", line 335, in <module>
    JustDiceBet()
  File "just-dice-bot.py", line 73, in **init**
    self.setUp()
  File "just-dice-bot.py", line 226, in setUp
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/webdriver.py", line 61, in **init**
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/extension_connection.py", line 47, in **init**
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 51, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.33.0-py2.7.egg/selenium/webdriver/firefox/firefox_binary.py", line 90, in _wait_until_connectable
    self._get_firefox_output())
selenium.common.exceptions.WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: cannot open display: :2842\n'

**Comment by KgBC** [comment]
The output was: Error: cannot open display: :2842

So this is an X-forwarding issue not related to the bot.
