### ISSUE TITLE
ImportError("matplotlib requires dateutil")

### ISSUE THREAD

**Issue by skynet21** [KgBC/just-dice-bot#48]
I tried installing and running this using Python 2.7. However, I get the following error:

D:\just-dice-bot-aces>cmd /k \python27\python just-dice-bot.py
Traceback (most recent call last):
  File "just-dice-bot.py", line 46, in <module>
    from matplotlib.figure import Figure  # @UnresolvedImport
  File "D:\python27\lib\site-packages\matplotlib__init__.py", line 111, in <module>
    raise ImportError("matplotlib requires dateutil")
ImportError: matplotlib requires dateutil

**Comment by rogeroyer** [comment]
Me too.
